AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'config/initializers/*'
    - 'config/environments/*'
    - 'bin/spring'
    - 'db/migrate/*'
Metrics/LineLength:
  Max: 100
Metrics/MethodLength:
  CountComments: false
  Max: 20
Metrics/AbcSize:
  Max: 35
Metrics/CyclomaticComplexity:
  Max: 7
